name: CI/CD Blog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run frontend tests
      run: |
        cd blog-frontend
        npm install
        npm run test -- --watchAll=false

    - name: Run backend tests
      run: |
        cd blog-api
        npm install
        npm run typeorm
        npm run test

    - name: Build frontend
      run: |
        cd blog-frontend
        npm run build

    - name: Build backend
      run: |
        cd blog-api
        npm run build
